[phases.setup]
aptPkgs = ["hugo", "git"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
  cmd = "hugo serve --port 3000"

[ environment ]
HUGO_VERSION = "0.147.3"
