[phases.setup]
aptPkgs = ["hugo", "git"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
  cmd = "hugo server --bind 0.0.0.0 --port 1313 --baseURL $URL"

[ environment ]
HUGO_VERSION = "0.147.3"
