[phases.setup]
aptPkgs = ["hugo", "git"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
    "cp -r .git /app/.git",
    "npm run build"
    ]

[start]
  cmd = "hugo server --bind 0.0.0.0 --baseURL http://website.open-elements.cloud --port 3000 --appendPort=false" 

[ environment ]
HUGO_VERSION = "0.147.3"
