providers = ["...", "node"]

[phases.setup]
nixPkgs = ["...", "nodejs_24"] 

[phases.install]
cmds = [
  "corepack enable", 
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node .next/server/server.js" 
