[phases.setup]
aptPkgs = ["hugo", "git"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
  cmd = "hugo server --bind 0.0.0.0 --port 1313 --baseURL http://x44koowcgw4wkcks8wkc4g00.91.99.108.179.sslip.io/"

[ environment ]
HUGO_VERSION = "0.147.3"
